# Generated by Django 3.1.7 on 2021-08-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentaddress1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROLLNO', models.CharField(max_length=200, null=True)),
                ('NAME', models.CharField(max_length=200, null=True)),
                ('FATHERNAME', models.CharField(max_length=200, null=True)),
                ('STUDYING', models.CharField(max_length=200, null=True)),
                ('ADDRESS', models.CharField(max_length=200, null=True)),
                ('PHONENO', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(upload_to='tatamotors/')),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
